### ISSUE TITLE
Erreur HelperTreeCategories

### ISSUE THREAD

**Issue by Clemweb** [pierre-b/affilae-prestashop#2]
Bonjour,

J'essaye de configurer le module sur un Prestashop 1.5.6.0 et j'obtient ce message lorsque je clique sur 'Ajouter une nouvelle règle de commissionnement' :

[PrestaShop] Fatal error in module affilae:
Class 'HelperTreeCategories' not found

Merci de votre aide

**Comment by pierre-b** [comment]
Bonjour Clemweb, le nouveau module Prestashop est disponible à https://github.com/AffilaeTech/affilae-prestashop , je vais delete ce repo d'ici quelques jours.

Cdlt
